service: simplequiz

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

custom:
  stage: ${opt:stage, self:provider.stage}
  appSync:
    name: ${self:service}-${self:custom.stage}-api
    authenticationType: AWS_IAM
    schema: schema.graphql
    additionalAuthenticationProviders:
      - authenticationType: API_KEY
    mappingTemplates:
      - dataSource: MainTableDataSource
        type: Mutation
        field: createQuiz
        request: "createQuiz-request.vtl"
        response: "createQuiz-response.vtl"
      - dataSource: MainTableDataSource
        type: Mutation
        field: joinQuiz
        request: "joinQuiz-request.vtl"
        response: "joinQuiz-response.vtl"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: MainTableDataSource
        description: Main Table for SimpleQuiz
        config:
          tableName: { Ref: MainTable }
          serviceRoleArn: { Fn::GetAtt: [AppSyncDynamoDBServiceRole, Arn] }

package:
  individually: true
  # exclude:
  #   - ./front/**
  #   - front/**

plugins:
  - serverless-bundle
  - serverless-appsync-plugin

resources:
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/roles.yml)}